#!/usr/bin/env bun
/**
 * Probe drizzle-kit studio's proxy endpoint with and without a bound
 * parameter.
 *
 * Studio's browser client sends raw SQL using Postgres-standard `$N`
 * placeholders. drizzle-orm's AwsPgDialect.escapeParam() returns `:${n + 1}`,
 * so SQL the ORM GENERATES is already in Data API form; but SQL that arrives
 * at kit's proxy is not generated by the dialect, and nothing translates it.
 *
 * The control (identical query, no parameters) isolates the failure to
 * parameter binding rather than to the query or the connection.
 *
 * Usage: bun scripts/probe-studio-proxy.ts [port]
 * Requires `drizzle-kit studio` to already be running on that port.
 */

const port = process.argv[2] ?? '4983';
const endpoint = `http://127.0.0.1:${port}/`;

async function proxy(sql: string, params: unknown[]) {
  const response = await fetch(endpoint, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ type: 'proxy', data: { sql, params, mode: 'object', method: 'all' } }),
  });
  return response.text();
}

const cases: [label: string, sql: string, params: unknown[]][] = [
  ['CONTROL: no parameters', 'select count(*)::text as n from regions', []],
  [
    'TEST: one bound parameter',
    'select count(*)::text as n from regions where country_code = $1',
    ['US'],
  ],
];

for (const [label, sql, params] of cases) {
  console.log(`\n### ${label}`);
  console.log(`sql:    ${sql}`);
  console.log(`params: ${JSON.stringify(params)}`);
  console.log(`result: ${(await proxy(sql, params)).slice(0, 300)}`);
}
